swagger: "2.0"



info:
  
	version: 1.0.0
 
	title: Passle API
  
	description: An API for Passle
  


schemes:
  
	- https

host: ec2-54-191-103-8.us-west-2.compute.amazonaws.com



paths: 
  
	/collections:
    
		get:
      
			summary: Gets collections
      
			description: Returns a list containing all collections
      
		responses:
        
			200:
          
				description: A list of Collections
          
				schema:
            
					type: array
            
					items:
              
						required:
                
							- order_no
              
						properties:
                
							delivered:
                  
								type: string
                
							picked_up:
                  
								type: string
                
							order_no:
                  
								type: string
   